basePath: /api
host: 127.0.0.1:8080
info:
  contact: {}
  description: |-
    #### 接口调用须知：
    **header请求头**
    ```shell
    Authorization: {{token}}  //登录凭证,token通过对应登录接口获取
    User-Role: user  //角色, user用户/admin管理员
    ```
  license:
    name: 项目地址
    url: https://gitee.com/wappyer/golang-backend-template.git
  title: golang后端接口项目模版
  version: "1.0"
paths: {}
swagger: "2.0"
tags:
- description: 登录相关
  name: login
- description: 用户信息相关
  name: user
- description: 信息配置相关
  name: info
